### ISSUE TITLE
%paddedtrack% option does not actually produce padded track numbers

### ISSUE THREAD

**Issue by ssstroke** [g-plane/cue-splitter#1]
The title is pretty much self-explanatory. Instead of expected `01., 02., 03., ...` it is just `1., 2,. 3., ...`. The number of tracks on the album I was trying to split is 7, maybe that is the reason, i.e. it no padding added if the number of tracks is less than 10? I can try an album with 10+ tracks to see how it goes when I have time.

By the way, great tool! Just found it and I enjoy it a lot. No more outdated standalone applications on my PC for this purpose. 💖

**Comment by g-plane** [comment]
You're right. It's based on the total number tracks. For example, if we have 100+ tracks, it will be "001.", "002." and so on. So, for a disc which contains no more than 10 tracks, it's just "1.", "2." and so on.
